# Generated by Django 4.2.13 on 2024-06-06 01:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MasterUserData',
            fields=[
                ('email', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'master_user_data',
            },
        ),
        migrations.CreateModel(
            name='RelationTable',
            fields=[
                ('email', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=20)),
                ('relation_email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Social_Media.masteruserdata')),
            ],
            options={
                'db_table': 'relation_table',
            },
        ),
    ]
